#!/bin/bash

#
# wi: A dead-simple git-based wiki
#
# Copyright (c) 2020 Rob Gulewich. All rights reserved.
#


if [[ -n $WI_PATH ]]; then
    DOC_PATH=$WI_PATH
    DOC_DIR=.
else
    WI_PATH=$HOME/.wi/wiki
    DOC_DIR=docs
    DOC_PATH=$WI_PATH/$DOC_DIR
fi

function mkp {
    mkdir -p $1
}

function use_git {
    if [[ -n $WI_GIT_DISABLED ]]; then
        return 1
    else
        return 0
    fi
}

function init {
    mkp $WI_PATH
    mkp $DOC_PATH
    cd $WI_PATH

    # XXX: check that we have git
    # XXX: suppress this msg?
    [[ ! -e $WI_PATH/.git ]] && use_git && git init
    [[ -z "$EDITOR" ]] && EDITOR=vim
}

function usage {
    me=$(basename $0)
cat - <<EOF
Usage:
    $me <topic>             Create or edit topic
    $me --list | --ls       List all topics

EOF
    exit 0
}

function edit {
    commit="false"
    file=$DOC_DIR/$1.md
    mode=create
    [[ -e $file ]] && mode=update
    $EDITOR $file
    [[ ! -e $file ]] && return
    if use_git; then
        if [[ $mode == "create" ]]; then
            git add $file
            commit="true"
        else
            [[ $(git status --porcelain | grep $file | awk '{print $1}') == "M" ]] && commit="true"
        fi
    else
        commit="false"
    fi

    [[ $commit == "true" ]] && git commit -m "$1 $mode" $file
}

function run_if_command {
    if [[ $1 == "--list" ]] || [[ $1 == "--ls" ]]; then
        ls $DOC_PATH | sed -e 's/.md$//'
        exit 0
    fi
    if [[ $1 == "--cmds" ]]; then
        cat - <<EOF
--list
EOF
        ls $DOC_PATH | sed -e 's/.md$//'
        exit 0
    fi
}

[[ -z $1 ]] && usage
init
run_if_command $1
edit $1
